Locals = {}

Locals = {
    ['en'] = { -- English
        ['TargetLabel'] = "Wash",
        ['ProgressLabel'] = "Washing hands...",
        ['SuccessTitle'] = "Success!",
        ['SuccessDescription'] = "You've successfully washed your hands, they're now as shiny as a diamond.",
        ['ErrorTitle'] = "Error!",
        ['ErrorDescription'] = "Something went wrong with cleaning your hands...",
    },
    ['nl'] = { -- Dutch/Nederlands
        ['TargetLabel'] = "Wassen",
        ['ProgressLabel'] = "Handen wassen...",
        ['SuccessTitle'] = "Success!",
        ['SuccessDescription'] = "Je hebt succesvol je handen gewassen, ze blinken nu net als diamanten!",
        ['ErrorTitle'] = "Fout!",
        ['ErrorDescription'] = "Er is iets misgegaan met het wassen van je handen...",
    },
    ['de'] = { -- German/Deutsch
        ['TargetLabel'] = "Waschen",
        ['ProgressLabel'] = "Hände waschen...",
        ['SuccessTitle'] = "Erfolg!",
        ['SuccessDescription'] = "Du hast erfolgreich deine Hände gewaschen, sie glänzen jetzt wie Diamanten!",
        ['ErrorTitle'] = "Fehler!",
        ['ErrorDescription'] = "Beim Händewaschen ist etwas schiefgegangen...",
    },
    ['fr'] = { -- French
        ['TargetLabel'] = "Laver",
        ['ProgressLabel'] = "Lavage des mains...",
        ['SuccessTitle'] = "Succès !",
        ['SuccessDescription'] = "Vous avez réussi à vous laver les mains, elles brillent maintenant comme des diamants !",
        ['ErrorTitle'] = "Erreur !",
        ['ErrorDescription'] = "Quelque chose s'est mal passé lors du lavage de vos mains...",
    },
    ['es'] = { -- Spanish/Español
        ['TargetLabel'] = "Lavar",
        ['ProgressLabel'] = "Lavando las manos...",
        ['SuccessTitle'] = "¡Éxito!",
        ['SuccessDescription'] = "Has lavado tus manos con éxito, ¡ahora brillan como diamantes!",
        ['ErrorTitle'] = "¡Error!",
        ['ErrorDescription'] = "Algo salió mal al lavar tus manos...",
    },
    ['it'] = { -- Italian/Italiano
        ['TargetLabel'] = "Lavare",
        ['ProgressLabel'] = "Lavaggio delle mani...",
        ['SuccessTitle'] = "Successo!",
        ['SuccessDescription'] = "Hai lavato le mani con successo, ora sono lucide come un diamante.",
        ['ErrorTitle'] = "Errore!",
        ['ErrorDescription'] = "Qualcosa è andato storto durante la pulizia delle mani...",
    },
    ['ar'] = { -- Arabic
        ['TargetLabel'] = "غسل",
        ['ProgressLabel'] = "غسيل اليدين...",
        ['SuccessTitle'] = "نجاح!",
        ['SuccessDescription'] = "لقد غسلت يديك بنجاح، الآن هما لامعتان كالماس.",
        ['ErrorTitle'] = "خطأ!",
        ['ErrorDescription'] = "حدث خطأ ما أثناء تنظيف يديك...",
    },
    ['tr'] = { -- Turkish
        ['TargetLabel'] = "Yıkama",
        ['ProgressLabel'] = "Elleri yıkama...",
        ['SuccessTitle'] = "Başarılı!",
        ['SuccessDescription'] = "Ellerini başarıyla yıkadın, şimdi elmas gibi parlıyorlar.",
        ['ErrorTitle'] = "Hata!",
        ['ErrorDescription'] = "Ellerini temizlemede bir sorun oluştu...",
    },               
}